//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BugTrackerModel", "FK_User_AccessLevel", "AccessLevel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DomainModel.Database.AccessLevel), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DomainModel.Database.User), true)]
[assembly: EdmRelationshipAttribute("BugTrackerModel", "FK_Bug_BugStatus", "BugStatu", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DomainModel.Database.BugStatus), "Bug", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DomainModel.Database.Bug), true)]
[assembly: EdmRelationshipAttribute("BugTrackerModel", "FK_Bug_Project", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DomainModel.Database.Project), "Bug", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DomainModel.Database.Bug), true)]
[assembly: EdmRelationshipAttribute("BugTrackerModel", "FK_Bug_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DomainModel.Database.User), "Bug", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DomainModel.Database.Bug), true)]
[assembly: EdmRelationshipAttribute("BugTrackerModel", "FK_Bug_User1", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DomainModel.Database.User), "Bug", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DomainModel.Database.Bug), true)]
[assembly: EdmRelationshipAttribute("BugTrackerModel", "FK_Project_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DomainModel.Database.User), "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DomainModel.Database.Project), true)]

#endregion

namespace DomainModel.Database
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BugTrackerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BugTrackerEntities object using the connection string found in the 'BugTrackerEntities' section of the application configuration file.
        /// </summary>
        public BugTrackerEntities() : base("name=BugTrackerEntities", "BugTrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BugTrackerEntities object.
        /// </summary>
        public BugTrackerEntities(string connectionString) : base(connectionString, "BugTrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BugTrackerEntities object.
        /// </summary>
        public BugTrackerEntities(EntityConnection connection) : base(connection, "BugTrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AccessLevel> AccessLevels
        {
            get
            {
                if ((_AccessLevels == null))
                {
                    _AccessLevels = base.CreateObjectSet<AccessLevel>("AccessLevels");
                }
                return _AccessLevels;
            }
        }
        private ObjectSet<AccessLevel> _AccessLevels;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bug> Bugs
        {
            get
            {
                if ((_Bugs == null))
                {
                    _Bugs = base.CreateObjectSet<Bug>("Bugs");
                }
                return _Bugs;
            }
        }
        private ObjectSet<Bug> _Bugs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BugStatus> BugStatus
        {
            get
            {
                if ((_BugStatus == null))
                {
                    _BugStatus = base.CreateObjectSet<BugStatus>("BugStatus");
                }
                return _BugStatus;
            }
        }
        private ObjectSet<BugStatus> _BugStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Project> Projects
        {
            get
            {
                if ((_Projects == null))
                {
                    _Projects = base.CreateObjectSet<Project>("Projects");
                }
                return _Projects;
            }
        }
        private ObjectSet<Project> _Projects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AccessLevels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccessLevels(AccessLevel accessLevel)
        {
            base.AddObject("AccessLevels", accessLevel);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bugs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBugs(Bug bug)
        {
            base.AddObject("Bugs", bug);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BugStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBugStatus(BugStatus bugStatus)
        {
            base.AddObject("BugStatus", bugStatus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Projects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjects(Project project)
        {
            base.AddObject("Projects", project);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackerModel", Name="AccessLevel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AccessLevel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AccessLevel object.
        /// </summary>
        /// <param name="access_Level_Id">Initial value of the Access_Level_Id property.</param>
        /// <param name="access_Level_Role">Initial value of the Access_Level_Role property.</param>
        public static AccessLevel CreateAccessLevel(global::System.Int32 access_Level_Id, global::System.String access_Level_Role)
        {
            AccessLevel accessLevel = new AccessLevel();
            accessLevel.Access_Level_Id = access_Level_Id;
            accessLevel.Access_Level_Role = access_Level_Role;
            return accessLevel;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Access_Level_Id
        {
            get
            {
                return _Access_Level_Id;
            }
            set
            {
                if (_Access_Level_Id != value)
                {
                    OnAccess_Level_IdChanging(value);
                    ReportPropertyChanging("Access_Level_Id");
                    _Access_Level_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Access_Level_Id");
                    OnAccess_Level_IdChanged();
                }
            }
        }
        private global::System.Int32 _Access_Level_Id;
        partial void OnAccess_Level_IdChanging(global::System.Int32 value);
        partial void OnAccess_Level_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Access_Level_Role
        {
            get
            {
                return _Access_Level_Role;
            }
            set
            {
                OnAccess_Level_RoleChanging(value);
                ReportPropertyChanging("Access_Level_Role");
                _Access_Level_Role = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Access_Level_Role");
                OnAccess_Level_RoleChanged();
            }
        }
        private global::System.String _Access_Level_Role;
        partial void OnAccess_Level_RoleChanging(global::System.String value);
        partial void OnAccess_Level_RoleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerModel", "FK_User_AccessLevel", "User")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("BugTrackerModel.FK_User_AccessLevel", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("BugTrackerModel.FK_User_AccessLevel", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackerModel", Name="Bug")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bug : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bug object.
        /// </summary>
        /// <param name="bug_Id">Initial value of the Bug_Id property.</param>
        /// <param name="bug_Description">Initial value of the Bug_Description property.</param>
        /// <param name="bug_Spotted_On">Initial value of the Bug_Spotted_On property.</param>
        /// <param name="bug_Spotted_By">Initial value of the Bug_Spotted_By property.</param>
        /// <param name="bug_Assigned_To">Initial value of the Bug_Assigned_To property.</param>
        /// <param name="bug_Status_Id">Initial value of the Bug_Status_Id property.</param>
        /// <param name="bug_Project_Id">Initial value of the Bug_Project_Id property.</param>
        public static Bug CreateBug(global::System.Int32 bug_Id, global::System.String bug_Description, global::System.DateTime bug_Spotted_On, global::System.Int32 bug_Spotted_By, global::System.Int32 bug_Assigned_To, global::System.Int32 bug_Status_Id, global::System.Int32 bug_Project_Id)
        {
            Bug bug = new Bug();
            bug.Bug_Id = bug_Id;
            bug.Bug_Description = bug_Description;
            bug.Bug_Spotted_On = bug_Spotted_On;
            bug.Bug_Spotted_By = bug_Spotted_By;
            bug.Bug_Assigned_To = bug_Assigned_To;
            bug.Bug_Status_Id = bug_Status_Id;
            bug.Bug_Project_Id = bug_Project_Id;
            return bug;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Bug_Id
        {
            get
            {
                return _Bug_Id;
            }
            set
            {
                if (_Bug_Id != value)
                {
                    OnBug_IdChanging(value);
                    ReportPropertyChanging("Bug_Id");
                    _Bug_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Bug_Id");
                    OnBug_IdChanged();
                }
            }
        }
        private global::System.Int32 _Bug_Id;
        partial void OnBug_IdChanging(global::System.Int32 value);
        partial void OnBug_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bug_Short_Description
        {
            get
            {
                return _Bug_Short_Description;
            }
            set
            {
                OnBug_Short_DescriptionChanging(value);
                ReportPropertyChanging("Bug_Short_Description");
                _Bug_Short_Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bug_Short_Description");
                OnBug_Short_DescriptionChanged();
            }
        }
        private global::System.String _Bug_Short_Description;
        partial void OnBug_Short_DescriptionChanging(global::System.String value);
        partial void OnBug_Short_DescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Bug_Description
        {
            get
            {
                return _Bug_Description;
            }
            set
            {
                OnBug_DescriptionChanging(value);
                ReportPropertyChanging("Bug_Description");
                _Bug_Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Bug_Description");
                OnBug_DescriptionChanged();
            }
        }
        private global::System.String _Bug_Description;
        partial void OnBug_DescriptionChanging(global::System.String value);
        partial void OnBug_DescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Bug_Spotted_On
        {
            get
            {
                return _Bug_Spotted_On;
            }
            set
            {
                OnBug_Spotted_OnChanging(value);
                ReportPropertyChanging("Bug_Spotted_On");
                _Bug_Spotted_On = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bug_Spotted_On");
                OnBug_Spotted_OnChanged();
            }
        }
        private global::System.DateTime _Bug_Spotted_On;
        partial void OnBug_Spotted_OnChanging(global::System.DateTime value);
        partial void OnBug_Spotted_OnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Bug_Spotted_By
        {
            get
            {
                return _Bug_Spotted_By;
            }
            set
            {
                OnBug_Spotted_ByChanging(value);
                ReportPropertyChanging("Bug_Spotted_By");
                _Bug_Spotted_By = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bug_Spotted_By");
                OnBug_Spotted_ByChanged();
            }
        }
        private global::System.Int32 _Bug_Spotted_By;
        partial void OnBug_Spotted_ByChanging(global::System.Int32 value);
        partial void OnBug_Spotted_ByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Bug_Assigned_To
        {
            get
            {
                return _Bug_Assigned_To;
            }
            set
            {
                OnBug_Assigned_ToChanging(value);
                ReportPropertyChanging("Bug_Assigned_To");
                _Bug_Assigned_To = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bug_Assigned_To");
                OnBug_Assigned_ToChanged();
            }
        }
        private global::System.Int32 _Bug_Assigned_To;
        partial void OnBug_Assigned_ToChanging(global::System.Int32 value);
        partial void OnBug_Assigned_ToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Bug_Status_Id
        {
            get
            {
                return _Bug_Status_Id;
            }
            set
            {
                OnBug_Status_IdChanging(value);
                ReportPropertyChanging("Bug_Status_Id");
                _Bug_Status_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bug_Status_Id");
                OnBug_Status_IdChanged();
            }
        }
        private global::System.Int32 _Bug_Status_Id;
        partial void OnBug_Status_IdChanging(global::System.Int32 value);
        partial void OnBug_Status_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Bug_Status_Time
        {
            get
            {
                return _Bug_Status_Time;
            }
            set
            {
                OnBug_Status_TimeChanging(value);
                ReportPropertyChanging("Bug_Status_Time");
                _Bug_Status_Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bug_Status_Time");
                OnBug_Status_TimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Bug_Status_Time;
        partial void OnBug_Status_TimeChanging(Nullable<global::System.DateTime> value);
        partial void OnBug_Status_TimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Bug_Attachment
        {
            get
            {
                return StructuralObject.GetValidValue(_Bug_Attachment);
            }
            set
            {
                OnBug_AttachmentChanging(value);
                ReportPropertyChanging("Bug_Attachment");
                _Bug_Attachment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bug_Attachment");
                OnBug_AttachmentChanged();
            }
        }
        private global::System.Byte[] _Bug_Attachment;
        partial void OnBug_AttachmentChanging(global::System.Byte[] value);
        partial void OnBug_AttachmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Bug_Project_Id
        {
            get
            {
                return _Bug_Project_Id;
            }
            set
            {
                OnBug_Project_IdChanging(value);
                ReportPropertyChanging("Bug_Project_Id");
                _Bug_Project_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bug_Project_Id");
                OnBug_Project_IdChanged();
            }
        }
        private global::System.Int32 _Bug_Project_Id;
        partial void OnBug_Project_IdChanging(global::System.Int32 value);
        partial void OnBug_Project_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerModel", "FK_Bug_BugStatus", "BugStatu")]
        public BugStatus BugStatu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BugStatus>("BugTrackerModel.FK_Bug_BugStatus", "BugStatu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BugStatus>("BugTrackerModel.FK_Bug_BugStatus", "BugStatu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BugStatus> BugStatuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BugStatus>("BugTrackerModel.FK_Bug_BugStatus", "BugStatu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BugStatus>("BugTrackerModel.FK_Bug_BugStatus", "BugStatu", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerModel", "FK_Bug_Project", "Project")]
        public Project Project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("BugTrackerModel.FK_Bug_Project", "Project").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("BugTrackerModel.FK_Bug_Project", "Project").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Project> ProjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("BugTrackerModel.FK_Bug_Project", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Project>("BugTrackerModel.FK_Bug_Project", "Project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerModel", "FK_Bug_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BugTrackerModel.FK_Bug_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BugTrackerModel.FK_Bug_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BugTrackerModel.FK_Bug_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("BugTrackerModel.FK_Bug_User", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerModel", "FK_Bug_User1", "User")]
        public User User1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BugTrackerModel.FK_Bug_User1", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BugTrackerModel.FK_Bug_User1", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> User1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BugTrackerModel.FK_Bug_User1", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("BugTrackerModel.FK_Bug_User1", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackerModel", Name="BugStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BugStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BugStatus object.
        /// </summary>
        /// <param name="bug_Status_Id">Initial value of the Bug_Status_Id property.</param>
        /// <param name="bug_Status_Name">Initial value of the Bug_Status_Name property.</param>
        public static BugStatus CreateBugStatus(global::System.Int32 bug_Status_Id, global::System.String bug_Status_Name)
        {
            BugStatus bugStatus = new BugStatus();
            bugStatus.Bug_Status_Id = bug_Status_Id;
            bugStatus.Bug_Status_Name = bug_Status_Name;
            return bugStatus;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Bug_Status_Id
        {
            get
            {
                return _Bug_Status_Id;
            }
            set
            {
                if (_Bug_Status_Id != value)
                {
                    OnBug_Status_IdChanging(value);
                    ReportPropertyChanging("Bug_Status_Id");
                    _Bug_Status_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Bug_Status_Id");
                    OnBug_Status_IdChanged();
                }
            }
        }
        private global::System.Int32 _Bug_Status_Id;
        partial void OnBug_Status_IdChanging(global::System.Int32 value);
        partial void OnBug_Status_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Bug_Status_Name
        {
            get
            {
                return _Bug_Status_Name;
            }
            set
            {
                OnBug_Status_NameChanging(value);
                ReportPropertyChanging("Bug_Status_Name");
                _Bug_Status_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Bug_Status_Name");
                OnBug_Status_NameChanged();
            }
        }
        private global::System.String _Bug_Status_Name;
        partial void OnBug_Status_NameChanging(global::System.String value);
        partial void OnBug_Status_NameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerModel", "FK_Bug_BugStatus", "Bug")]
        public EntityCollection<Bug> Bugs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Bug>("BugTrackerModel.FK_Bug_BugStatus", "Bug");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Bug>("BugTrackerModel.FK_Bug_BugStatus", "Bug", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackerModel", Name="Project")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Project : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="project_Id">Initial value of the Project_Id property.</param>
        /// <param name="project_Name">Initial value of the Project_Name property.</param>
        /// <param name="project_Manager_Id">Initial value of the Project_Manager_Id property.</param>
        public static Project CreateProject(global::System.Int32 project_Id, global::System.String project_Name, global::System.Int32 project_Manager_Id)
        {
            Project project = new Project();
            project.Project_Id = project_Id;
            project.Project_Name = project_Name;
            project.Project_Manager_Id = project_Manager_Id;
            return project;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Project_Id
        {
            get
            {
                return _Project_Id;
            }
            set
            {
                if (_Project_Id != value)
                {
                    OnProject_IdChanging(value);
                    ReportPropertyChanging("Project_Id");
                    _Project_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Project_Id");
                    OnProject_IdChanged();
                }
            }
        }
        private global::System.Int32 _Project_Id;
        partial void OnProject_IdChanging(global::System.Int32 value);
        partial void OnProject_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Project_Name
        {
            get
            {
                return _Project_Name;
            }
            set
            {
                OnProject_NameChanging(value);
                ReportPropertyChanging("Project_Name");
                _Project_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Project_Name");
                OnProject_NameChanged();
            }
        }
        private global::System.String _Project_Name;
        partial void OnProject_NameChanging(global::System.String value);
        partial void OnProject_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Project_Manager_Id
        {
            get
            {
                return _Project_Manager_Id;
            }
            set
            {
                OnProject_Manager_IdChanging(value);
                ReportPropertyChanging("Project_Manager_Id");
                _Project_Manager_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Project_Manager_Id");
                OnProject_Manager_IdChanged();
            }
        }
        private global::System.Int32 _Project_Manager_Id;
        partial void OnProject_Manager_IdChanging(global::System.Int32 value);
        partial void OnProject_Manager_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerModel", "FK_Bug_Project", "Bug")]
        public EntityCollection<Bug> Bugs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Bug>("BugTrackerModel.FK_Bug_Project", "Bug");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Bug>("BugTrackerModel.FK_Bug_Project", "Bug", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerModel", "FK_Project_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BugTrackerModel.FK_Project_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BugTrackerModel.FK_Project_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BugTrackerModel.FK_Project_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("BugTrackerModel.FK_Project_User", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackerModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="user_Id">Initial value of the User_Id property.</param>
        /// <param name="user_Name">Initial value of the User_Name property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="first_Name">Initial value of the First_Name property.</param>
        /// <param name="last_Name">Initial value of the Last_Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="access_Level_Id">Initial value of the Access_Level_Id property.</param>
        public static User CreateUser(global::System.Int32 user_Id, global::System.String user_Name, global::System.String password, global::System.String first_Name, global::System.String last_Name, global::System.String email, global::System.Int32 access_Level_Id)
        {
            User user = new User();
            user.User_Id = user_Id;
            user.User_Name = user_Name;
            user.Password = password;
            user.First_Name = first_Name;
            user.Last_Name = last_Name;
            user.Email = email;
            user.Access_Level_Id = access_Level_Id;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 User_Id
        {
            get
            {
                return _User_Id;
            }
            set
            {
                if (_User_Id != value)
                {
                    OnUser_IdChanging(value);
                    ReportPropertyChanging("User_Id");
                    _User_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("User_Id");
                    OnUser_IdChanged();
                }
            }
        }
        private global::System.Int32 _User_Id;
        partial void OnUser_IdChanging(global::System.Int32 value);
        partial void OnUser_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User_Name
        {
            get
            {
                return _User_Name;
            }
            set
            {
                OnUser_NameChanging(value);
                ReportPropertyChanging("User_Name");
                _User_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User_Name");
                OnUser_NameChanged();
            }
        }
        private global::System.String _User_Name;
        partial void OnUser_NameChanging(global::System.String value);
        partial void OnUser_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String First_Name
        {
            get
            {
                return _First_Name;
            }
            set
            {
                OnFirst_NameChanging(value);
                ReportPropertyChanging("First_Name");
                _First_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("First_Name");
                OnFirst_NameChanged();
            }
        }
        private global::System.String _First_Name;
        partial void OnFirst_NameChanging(global::System.String value);
        partial void OnFirst_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Last_Name
        {
            get
            {
                return _Last_Name;
            }
            set
            {
                OnLast_NameChanging(value);
                ReportPropertyChanging("Last_Name");
                _Last_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Last_Name");
                OnLast_NameChanged();
            }
        }
        private global::System.String _Last_Name;
        partial void OnLast_NameChanging(global::System.String value);
        partial void OnLast_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Access_Level_Id
        {
            get
            {
                return _Access_Level_Id;
            }
            set
            {
                OnAccess_Level_IdChanging(value);
                ReportPropertyChanging("Access_Level_Id");
                _Access_Level_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Access_Level_Id");
                OnAccess_Level_IdChanged();
            }
        }
        private global::System.Int32 _Access_Level_Id;
        partial void OnAccess_Level_IdChanging(global::System.Int32 value);
        partial void OnAccess_Level_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Send_Bug_Email
        {
            get
            {
                return _Send_Bug_Email;
            }
            set
            {
                OnSend_Bug_EmailChanging(value);
                ReportPropertyChanging("Send_Bug_Email");
                _Send_Bug_Email = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Send_Bug_Email");
                OnSend_Bug_EmailChanged();
            }
        }
        private Nullable<global::System.Boolean> _Send_Bug_Email;
        partial void OnSend_Bug_EmailChanging(Nullable<global::System.Boolean> value);
        partial void OnSend_Bug_EmailChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerModel", "FK_User_AccessLevel", "AccessLevel")]
        public AccessLevel AccessLevel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AccessLevel>("BugTrackerModel.FK_User_AccessLevel", "AccessLevel").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AccessLevel>("BugTrackerModel.FK_User_AccessLevel", "AccessLevel").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AccessLevel> AccessLevelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AccessLevel>("BugTrackerModel.FK_User_AccessLevel", "AccessLevel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AccessLevel>("BugTrackerModel.FK_User_AccessLevel", "AccessLevel", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerModel", "FK_Bug_User", "Bug")]
        public EntityCollection<Bug> Bugs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Bug>("BugTrackerModel.FK_Bug_User", "Bug");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Bug>("BugTrackerModel.FK_Bug_User", "Bug", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerModel", "FK_Bug_User1", "Bug")]
        public EntityCollection<Bug> Bugs1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Bug>("BugTrackerModel.FK_Bug_User1", "Bug");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Bug>("BugTrackerModel.FK_Bug_User1", "Bug", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerModel", "FK_Project_User", "Project")]
        public EntityCollection<Project> Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("BugTrackerModel.FK_Project_User", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("BugTrackerModel.FK_Project_User", "Project", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
